### ISSUE TITLE
Failed to open stream: HTTP request failed

### ISSUE THREAD

**Issue by GenTxt** [roelfrenkema/clsStraico#1]
As a straico user thanks for the repo. I'm looking forward to using a more extensive api compared to the examples on the website. Currently using a simple python script that returns unformatted replies.

Downloaded latest version from github. Using 'PHP 8.1.2-1ubuntu2.14 (cli)', ubuntu 22.04

After adding valid straico api key ran 'php prompt.php' :

PHP Warning:  file_get_contents(https://api.straico.com/v0/user): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /home/pix/STRAICO/clsStraico-main/clsStraico.php on line 758
 
PHP Warning:  file_get_contents(https://api.straico.com/v0/models): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /home/pix/STRAICO/clsStraico-main/clsStraico.php on line 729
 
PHP Warning:  Trying to access array offset on value of type null in /home/pix/STRAICO/clsStraico-main/prompt.php on line 25

PHP Warning:  Trying to access array offset on value of type null in /home/pix/STRAICO/clsStraico-main/prompt.php on line 25

Welcome  to google/gemini-pro. Please ask your questions.

For help enter /gethelp.
When done finish with /exit.

> What is the capital of Peru?

Error: file_get_contents(https://api.straico.com/v0/prompt/completion): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized

Oops I could not process your request please inform the developer.

###############

In both cases it's this line:

$result = file_get_contents($endPoint, false, $context);

Don't use php often so not sure what the issue is. Is there a better command to run the script?

Thanks

**Comment by roelfrenkema** [comment]
Seems like the class can't find your api key here. Make sure you have environment variable
**STRAICO_APIKEY** setup properly before you start prompt.php and that it has the correct key without typos. If it still not works it seems to be a problem with the key and you best contact Straico support.

**Comment by roelfrenkema** [comment]
As this is strictly an API key problem I added a check in the corresponding code that will warn and exit the class. The ApiKey check is part of _construct to get the user data. This way it will be executed and tested even before the prompt appears. You will just get the warning:

Error:  HTTP request failed! HTTP/1.1 401 Unauthorized
Check your API key!

The repo was updated.

Thank you for bringging this to my attention.

**Comment by GenTxt** [comment]
Thanks for the update. 

As I mentioned above I can use a simple python script with my current api key so that's not the issue.

Not familiar with php but I did manage to get it working by commenting out:

$this->apiKey = getenv('Bearer 8k-valid_straico_api_key'); 

then editing 3x lines:

'header' => "Authorization: Bearer ".$this->apiKey."\r\n", # comment out 3x

change to:
			
'header' => "Authorization: Bearer 8k-valid_straico_api_key\r\n",

Have no doubt original works but if someone else has the same issues this is what worked in my case.

Feel free to close.

**Comment by roelfrenkema** [comment]
Your April fools joke is on you and impoved my code , again thank you.
